#端口号
server:
  port: 8080

#druid数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/warehousesystem?useSSL=true&serverTimezone=GMT&characterEncoding=utf8
      username: root
      password: 13597803422dw
#      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver

#开启mybatis plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #开启逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
