#服务端口
server:
  port: 8080

#druid连接池配置
spring:
  datasource:
    druid:
      #mysql8.0+的额外操作
      url: jdbc:mysql://localhost:3306/StudentWorkSystem?serverTimezone=GMT&useUnicode=true&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 13597803422dw

#开启mybatis plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    #逻辑删除
    mybatis-plus:
      global-config:
        db-config:
          logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
          logic-delete-value: 1 # 逻辑已删除值(默认为 1)
          logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
