#web服务端口
server:
  port: 8080

#druid连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeawaysystem?userSSL=true&serverTimezone=GMT
      username: root
      password: 13597803422dw

#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #开启日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl